---
- name: test if anaconda_python_version is set correctly
  assert:
    that:
      - anaconda_python_version is defined
      - anaconda_python_version is number
      - anaconda_python_version in [ 2, 3 ]
    quiet: yes

- name: test if anaconda_version is set correctly
  assert:
    that:
      - anaconda_version is defined
    quiet: yes

- name: test if anaconda_ip is set correctly
  assert:
    that:
      - anaconda_ip is defined
    quiet: yes

- name: test if anaconda_port is set correctly
  assert:
    that:
      - anaconda_port is defined
      - anaconda_port is number
      - anaconda_port | int > 0
      - anaconda_port | int < 65536
    quiet: yes

- name: test if anaconda_download_dest is set correctly
  assert:
    that:
      - anaconda_download_dest is defined
    quiet: yes

- name: test if anaconda_prefix is set correctly
  assert:
    that:
      - anaconda_prefix is defined
    quiet: yes
